CREATE TABLE `payment_order` (
                                 `id` BIGINT NOT NULL PRIMARY KEY,
                                 `payment_no` VARCHAR(64) NOT NULL,
                                 `order_id` BIGINT NOT NULL,
                                 `order_no` VARCHAR(64) NOT NULL,
                                 `user_id` BIGINT NOT NULL,
                                 `payment_channel` VARCHAR(32) NOT NULL COMMENT 'WECHAT_NATIVE',
                                 `amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
                                 `status` TINYINT NOT NULL DEFAULT 10 COMMENT '10-支付中 20-支付成功 30-已关闭 40-支付失败 50-异常单',
                                 `out_trade_no` VARCHAR(64) NOT NULL,
                                 `provider_trade_no` VARCHAR(64) DEFAULT NULL,
                                 `code_url` VARCHAR(512) DEFAULT NULL,
                                 `prepay_payload` TEXT DEFAULT NULL,
                                 `notify_payload` LONGTEXT DEFAULT NULL,
                                 `provider_status` VARCHAR(32) DEFAULT NULL,
                                 `error_code` VARCHAR(64) DEFAULT NULL,
                                 `error_message` VARCHAR(255) DEFAULT NULL,
                                 `expire_time` DATETIME DEFAULT NULL,
                                 `success_time` DATETIME DEFAULT NULL,
                                 `close_time` DATETIME DEFAULT NULL,
                                 `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                 UNIQUE KEY `uk_payment_no` (`payment_no`),
                                 UNIQUE KEY `uk_out_trade_no` (`out_trade_no`),
                                 KEY `idx_order_id` (`order_id`),
                                 KEY `idx_status_expire_time` (`status`, `expire_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
