server:
  port: 8080

spring:
  application:
    name: ai-flash-sale

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ai_flash_schema
    username: root
    password: 11899746qa
    driverClassName: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000ms

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: assign_id

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ai-flash-sale-order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.weijinchuan.aiflashsale.event

qwen:
  base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
  api-key: ${DASHSCOPE_API_KEY:}
  model: qwen-plus

rag:
  knowledge-base-location: ai/knowledge-base.json
  retrieval:
    default-top-k: 4
    preview-length: 88

outbox:
  retry:
    fixed-delay-ms: 10000
    batch-size: 20
    max-attempts: 8
    backoff-seconds: 30

order:
  timeout:
    minutes: 30
    close:
      fixed-delay-ms: 10000
      batch-size: 20

logging:
  level:
    org.apache.kafka: info
    com.weijinchuan.aiflashsale: info
